### ISSUE TITLE
data-ic/data-nice has not been updated since july 8

### ISSUE THREAD

**Issue by fmeijers** [J535D165/CoronaWatchNL#151]
Hello, I see that the data with regard to the intensive care has not been updated since July 8. Is that not going to happen again, or will it be resumed? If the latter is the case, is it already known from when?? Thanks.

**Comment by J535D165** [comment]
Hi @fmeijers, 

I did an update of the data. I thought, maybe it is fine to do weekly update for this dataset as well. But if you are unhappy with this, I can have a look on updating this more regularly. The main issue is that automating this pipeline is a bit challenging because nice is blocking so many IP-addresses.

**Comment by Sikerdebaard** [comment]
@J535D165 if it helps any I'm mirroring the api output to this repo once an hour. This should be accessible by github pipelines. The data extraction pipeline itself is running on a VM in a hospital so it is unlikely that it's going to be blocked.

https://github.com/Sikerdebaard/dutchcovid19data

**Comment by J535D165** [comment]
Great! I will start using this and automate with GH Actions

**Comment by fmeijers** [comment]
Hi, Thanks for your quick responses and solutions. It would be great if the data will be refreshed on a daily basis (or even more frequent;-). I use these data in my Covid-19 dashboard in which all other data is refreshed on a daily basis: bit.ly/COVID-19-DB
