### ISSUE TITLE
Total number of tests per week deviates from sources

### ISSUE THREAD

**Issue by realrolfje** [J535D165/CoronaWatchNL#179]
The file https://raw.githubusercontent.com/J535D165/CoronaWatchNL/master/data-misc/data-test/RIVM_NL_test_latest.csv shows the total number of tests, but the number is significantly lower than the GHOR and RIVM data:

| Week | Coronawatch | GHOR    | RIVM    |
|-----:|------------:|--------:|--------:|
|   42 |     213.045 | 311.188 | 285.277 |
|   43 |     197.020 | 321.654 | 310.716 |

GHOR data from https://ggdghor.nl/actueel-bericht/weekupdate-cijfers-coronatests-bij-de-ggden-2/
RIVM data from https://www.rivm.nl/coronavirus-covid-19/actueel

Is this by design, and/or is there a source for getting the GHOR or RIVM numbers?

**Comment by realrolfje** [comment]
I think I found it:
On page 27 of COVID-19_epidemiological_report_20201027.pdf the number of tests match the GHOR/RIVM numbers.

On page 42 of COVID-19_epidemiological_report_20201027.pdf, the number of tested persons is reported, which is lower (the same person can be tested twice, but counts as 1 person).

The GHOR and RIVM sites report total number of tests, CoronaWatch reports number of people tested. BUT: On the RIVM website, it prints "total positive persons" (not total positive tests) and calculates a percentage against the total number of tests, which is currently 15%, but in the report the right numbers are compared, which results in 17%. on page 27.

Maybe it is a good idea to have these numbers in one overview/datafile, with a good description of what the numbers mean.

**Comment by Sikerdebaard** [comment]
Potentially related to #176

**Comment by realrolfje** [comment]
Correct, #176 shows the same difference. It means that roughly 30% of tests are on the same person in that month:
Page 27: "Totaal aantal testen met uitslag"
Pave 41: "Aantal geteste personen"

**Comment by J535D165** [comment]
Hmm, thank you for your thoughts on this topic. The explainability and quality of the test data are concerning (since the first day it was available). The numbers are hard to match with the daily positively tested persons. I will have a look at your idea. For now, I decided to add a reference to the source of the data in the CSV files and added a new file with GGD-GHOR data.  

GGD-GHOR data: https://github.com/J535D165/CoronaWatchNL/tree/master/data-misc#test-data-ggd-ghor
Source variable in test data (section 11 of pdf):  https://github.com/J535D165/CoronaWatchNL/tree/master/data-misc#test-data-virologische-dagstaten

Tomorrow, I will have a more detailed look. This table is also interesting:

![image](https://user-images.githubusercontent.com/12981139/97816981-c4aa4800-1c99-11eb-8d99-70e3c472b916.png)

**Comment by Sikerdebaard** [comment]
Here's a snippet that automatically extracts the table from the GGD page.

```from bs4 import BeautifulSoup
import requests

headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Max-Age': '3600',
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'
}

url = 'https://ggdghor.nl/nieuws/'
req = requests.get(url, headers)
soup = BeautifulSoup(req.content, 'html.parser')

urls = set()

for a in soup.find_all('a', href=True):
    if 'coronatests' in a['href']:
        urls.add(a['href'])
        
urls = list(urls)

import pandas as pd
import dateparser

df_tests = pd.read_html(urls[0], header=0)[0]
df_tests.columns = ['week', 'tests']

df_tests['tests'] = [int(t.replace('.', '')) for t in df_tests['tests']]
total = df_tests['tests'].iloc[-1]

df_tests = df_tests[:-1]  # remove totals row

df_tests['week'] = pd.to_datetime([dateparser.parse(d.lower().split('t/m')[1].strip()) for d in df_tests['week']]).week

df_tests.set_index('week', inplace=True)
df_tests.rename(columns={'tests': 'ggd-tests'}, inplace=True)

df_tests.to_csv('ggd-tests.csv')`
