### ISSUE TITLE
Improve sigmoid simulations

### ISSUE THREAD

**Issue by vmenger** [J535D165/CoronaWatchNL#23]
Do you have any suggestions how to improve the simulations of the sigmoid fitting? Currently it samples known data points (with replacement), but the range is almost certainly way too low. 

If have also tried inferring data for the two next days, sampled from the distribution of the growth factor of the last five days. But I doubt the resulting image is still useful/readable: 

![sigmoid-with-two-inferred-days](https://user-images.githubusercontent.com/30691574/76690613-f191e800-6641-11ea-818d-dd7ceab55a1f.png)

Any suggestions are very welcome.

**Comment by japhir** [comment]
Maybe this is all the predictive power a simple sigmoid fit has right now, with 4 parameters fit to 15ish data points. What does it look like when you plot on a log scale?

**Comment by japhir** [comment]
In [this cool article](https://medium.com/@tomaspueyo/coronavirus-act-today-or-people-will-die-f4d3d9cd99ca) they mention that enacting social distancing **one day** earlier results in 40% fewer cases in the end. So that means that what we're going to see really heavily depends on what we're doing now and on what the data show during the next few days. I think it would be helpful to show this uncertainty.

**Comment by J535D165** [comment]
Really detailed. Very nice. 

btw @vmenger, your model fits well today.

**Comment by japhir** [comment]
@vmenger could you also update the appropriate readme to explain this resampling procedure? :)

**Comment by vmenger** [comment]
Yes, will do, but I think it's best to wait for #32 to avoid duplicate work.
