### ISSUE TITLE
Reconstruct data of March 2

### ISSUE THREAD

**Issue by J535D165** [J535D165/CoronaWatchNL#5]
Since 3 March, RIVM reports the number of diagnoses with the coronavirus and their municipality of residence on a daily basis. This issue is used to reconstruct the data of March 1 based on RIVM media reports.

Result: 
- 1 person from Tilburg
- 1 person from Diemen
- ...

**Comment by JochemZ** [comment]
3-3-2020 has 8 missing for Unknown, 16-3-2020 has 1 missing for maasdriel and unknown is to high (+2), 17-3-2020 has 1 missing for unknown?

**Comment by J535D165** [comment]
Thanks!

3-3-2020:

2020-03-03,Coevorden,109,Drenthe,2
2020-03-03,Houten,321,Utrecht,1
2020-03-03,Utrecht,344,Utrecht,2
2020-03-03,Diemen,384,Noord-Holland,3
2020-03-03,Haarlem,392,Noord-Holland,1
2020-03-03,Alphen aan den Rijn,484,Zuid-Holland,1
2020-03-03,Delft,503,Zuid-Holland,1
2020-03-03,Rotterdam,599,Zuid-Holland,1
2020-03-03,Eindhoven,772,Noord-Brabant,1
2020-03-03,Helmond,794,Noord-Brabant,1
2020-03-03,Loon op Zand,809,Noord-Brabant,4
2020-03-03,Oss,828,Noord-Brabant,1
2020-03-03,Tilburg,855,Noord-Brabant,2
2020-03-03,Altena,1959,Noord-Brabant,3

Sums to 24. This is the reported number, isn't it?

There is a minor difference between the reported number of RIVM on the news publication and the numbers they provide.  Can you elaborate a bit more on your findings and ideas to improve the data quality?

Thanks in advance

**Comment by JochemZ** [comment]
To make my data correct (according data published in the news) I have to some changes to the data:

16-03-2020,Onbekend,-2
16-03-2020,Maasdriel,1
17-03-2020,Onbekend,1
18-03-2020,Onbekend,-1

I think the problem is in the unknown data from RIVM, these are my results now (after correction):
Onbekend | 02-03-2020 | 8
Onbekend | 03-03-2020 | 8
Onbekend | 04-03-2020 | 1
Onbekend | 05-03-2020 | 5
Onbekend | 06-03-2020 | 4
Onbekend | 07-03-2020 | 4
Onbekend | 08-03-2020 | 2
Onbekend | 09-03-2020 | 1
Onbekend | 10-03-2020 | 2
Onbekend | 11-03-2020 | 6
Onbekend | 12-03-2020 | 13
Onbekend | 13-03-2020 | 29
Onbekend | 14-03-2020 | 38
Onbekend | 15-03-2020 | 59
Onbekend | 16-03-2020 | 69
Onbekend | 17-03-2020 | 72
Onbekend | 18-03-2020 | 84

**Comment by JochemZ** [comment]
Yesterday the unknown category was missing +89

**Comment by J535D165** [comment]
Thanks, counting one more:

```
2033  2020-03-19                NaN            -1           NaN      90
```

I think I have to exclude the foreigner(s).

**Comment by J535D165** [comment]
Maybe we should document this, there is quite some discussion on the way I'm saving the unknowns.

**Comment by JochemZ** [comment]
90 will give me 2461 the rivm site and the news told me 2460, rise is 410 (with value 90) instead of 409 compared to 18-3-2020

**Comment by japhir** [comment]
Has this been fixed? Should this behaviour be documented @J535D165?

**Comment by J535D165** [comment]
Yes, this is resolved by ignoring the reported counts and derive them from the national case count and the sum of all municipalities.

About reconstructing the data of March 2, I don't think this is doable. I asked RIVM for a backfill, but I don't think this is about the happen. So let's close this issue. Drop a message if you think we should reopen this issue.
