### ISSUE TITLE
Missing daterange rivm_NL_covid19_total_municipality.csv

### ISSUE THREAD

**Issue by BasSchnater** [J535D165/CoronaWatchNL#62]
Hi Jonathan,

First of all: fantastic effort by pulling all of this together. It helps many people from many industries (like mine: publishing) to make the data accessible.

Question about rivm_NL_covid19_total_municipality.csv: the dataset seems to be jumping from 31-mrt to 8-apr. Do you know a way how to get the missing data available? I tried to copy/paste from different dataset but there always seems to be a problem (day count vs. cum. count etc.)

**Comment by J535D165** [comment]
This part of the data isn't available on the municipality level because RIVM didn't publish it. For a couple of days, RIVM publishes this part of the data again. Unfortunately, this breaks the time series. We are in contact with RIVM about this issue. See #44.

Alternatives:
 - Number of hospitalized patients: https://github.com/J535D165/CoronaWatchNL/blob/master/data/rivm_NL_covid19_hosp_municipality.csv
 - Patients per 100k residents extracted from the PDF maps: https://github.com/J535D165/CoronaWatchNL/blob/master/data/rivm_NL_covid19_municipality_range.csv (See #48)

Feel free to send me an email for more help
