### ISSUE TITLE
Intensive Care data from NICE

### ISSUE THREAD

**Issue by elvissey1984** [J535D165/CoronaWatchNL#72]
First of all thank you so much for the efforts! It was the best efforts on getting all the numbers together I saw and thank you for that.

Regarding the IC data from NICE... understand you said it was experimental but I noticed that it has stopped updating for 4 days. What's the plan on this? Is there temporary issues on getting the data, or is this dataset being deprecated?

thanks!

**Comment by J535D165** [comment]
NICE changed a couple of things. Unfortunately, there was no time to work on this during the week. Today I will post the updated dataset (Struggling with one column).

There is a lot more in this dataset, so I'm working on some scripts to extract this as well. When this is done, I will remove the experimental flag.

Sorry for the inconvenience.

**Comment by elvissey1984** [comment]
Thank you for the help! Looking forward this the new dataset.

A related question: I saw you have IC data from another source and the reading is quite different - how would you read into this? Which one would you think is more trustworthy/accurate?

**Comment by janvanmastbergen** [comment]
I noticed that the new-intake data set from the nice site is the only one to contain 2 series instead of 1 as do the others. Both series show the same date range as any other but the values differ significantly. How di I read this?

KR, Jan van Mastbergen

**Comment by J535D165** [comment]
@elvissey1984 The one of LCPS is very useful because it gives an accurate overview. It is updated once a day. NICE has more variables and is updated multiple times a day. The latter one is something you have to keep in mind for some applications. 

@janvanmastbergen First col is the actual number. The second is the number of patients not tested yet, but highly likely affected by the virus. Therefore, the difference is large.
