### ISSUE TITLE
Cumulative data not always cumulative

### ISSUE THREAD

**Issue by Sikerdebaard** [J535D165/CoronaWatchNL#96]
It seems that data that should be cumulative is not always cumulative. Is there a reason behind this?

E.g. the following script checks if values are cumulative for the ```data-geo/data-municipal/RIVM_NL_municipal.csv``` dataset.

```python
import pandas as pd

df_cum_test = pd.read_csv('https://github.com/J535D165/CoronaWatchNL/raw/master/data-geo/data-municipal/RIVM_NL_municipal.csv', index_col=0)
df_cum_test.index = pd.to_datetime(df_cum_test.index)

types = set(df_cum_test['Type'])
municipalities = set(df_cum_test['Gemeentecode'])

for t in types:
    for municipality in municipalities:
        df_tmp = df_cum_test[(df_cum_test['Type'] == t) & (df_cum_test['Gemeentecode'] == municipality)]
        df_tmp.sort_index(inplace=True)
        cum_diff = df_tmp['AantalCumulatief'].diff().values
        
        if any(cum_diff < 0):
            print(f'Cumulative numbers are not cumulative for gemeente {municipality} on type {t}.')
            print(df_tmp['AantalCumulatief'].values)
```

Currently the script produces around 136 violations that look like this. Some of these could perhaps be fixed with a df.fillna(method='ffill') to forward-fill the nan values. Others are not so easily fixed.

```
Cumulative numbers are not cumulative for gemeente 47 on type Totaal.
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  2.  2.  2. nan nan nan
 nan nan nan nan nan  5.  5.  6.  6.  7.  7.  7.  8.  8.  8.  8.  8.  8.
  8.  8.  8.  9.  9.  9.  9.  9.  8.  8.  8.  8.  8.]
Cumulative numbers are not cumulative for gemeente 119 on type Totaal.
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  1.  1.  1.  3.  3.  3.  3.  4.  6.  8.  8. nan nan nan
 nan nan nan nan nan 21. 21. 21. 24. 24. 25. 25. 25. 25. 26. 26. 27. 28.
 28. 28. 31. 31. 31. 31. 30. 30. 31. 31. 31. 31. 31.]
```

**Comment by J535D165** [comment]
Thanks again @Sikerdebaard. 

These are data corrections by RIVM I think. Consider the municipality of Brummen
```
Cumulative numbers are not cumulative for gemeente 213 on type Overleden.
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  5.  5.  5.
  6.  6.  6.  6.  6.  6.  6.  7.  7.  7.  5.  5.  5.]
```

Check the raw data: 

https://github.com/J535D165/CoronaWatchNL/blob/bb97e3b4d4c95f8299eea7e17e419bb6663344fd/raw_data/peildatum-29-04-2020-14-00.csv#L55
https://github.com/J535D165/CoronaWatchNL/blob/bb97e3b4d4c95f8299eea7e17e419bb6663344fd/raw_data/peildatum-30-04-2020-14-00.csv#L55
https://github.com/J535D165/CoronaWatchNL/blob/bb97e3b4d4c95f8299eea7e17e419bb6663344fd/raw_data/peildatum-01-05-2020-14-00.csv#L55
https://github.com/J535D165/CoronaWatchNL/blob/bb97e3b4d4c95f8299eea7e17e419bb6663344fd/raw_data/peildatum-02-05-2020-14-00.csv#L55
https://github.com/J535D165/CoronaWatchNL/blob/bb97e3b4d4c95f8299eea7e17e419bb6663344fd/raw_data/peildatum-03-05-2020-14-00.csv#L55

Filling the `nan` values is tricky in my opinion. I think I prefer to leave this imputation up to the user for now. Hopefully, RIVM will backfill their data and the problem is solved. 

Does this answer your question? Feel free to your thoughts on this.  

@RVoor

**Comment by Sikerdebaard** [comment]
Ah yes, this indeed seems to be the case. Would it be reasonable to add a warning for the affected datasets?

**Comment by Sikerdebaard** [comment]
In case you guys ever change your mind, here's a script I'm using to correct the data. This script will first ffill any nan-values where possible. It then makes sure that any new values that are lower than the previous values propogate backwards. This seems reasonable for now.

```python
import pandas as pd

def check_if_cumulative(df_test):
    types = set(df_test['Type'])
    municipalities = set(df_test['Gemeentecode'])
    is_cumulative = True
    
    for t in types:
        for municipality in municipalities:
            df_tmp = df_test[(df_test['Type'] == t) & (df_test['Gemeentecode'] == municipality)]
            df_tmp.sort_index(inplace=True)
            cum_diff = df_tmp['AantalCumulatief'].diff().values

            if any(cum_diff < 0):
                print(df_tmp.values)
                is_cumulative = False
                
    return is_cumulative

def fix_cumulative_vals(df_fix):
    types = set(df_fix['Type'])
    municipalities = set(df_fix['Gemeentecode'])

    for t in types:
        for municipality in municipalities:
            df_tmp = df_fix[(df_fix['Type'] == t) & (df_fix['Gemeentecode'] == municipality)].copy()
            df_tmp.sort_index(inplace=True)
            cum_diff = df_tmp['AantalCumulatief'].diff().values

            if any(cum_diff < 0):  # RIVM made some changes
                df_tmp['AantalCumulatief'] = df_tmp['AantalCumulatief'].fillna(method='ffill')

                vals = df_tmp['AantalCumulatief'].values

                for i in reversed(range(1, len(vals))):
                    if vals[i] < vals[i-1]:
                        vals[i-1] = vals[i]

                df_fix.loc[(df_fix['Type'] == t) & (df_fix['Gemeentecode'] == municipality), 'AantalCumulatief'] = vals


df = pd.read_csv('https://github.com/J535D165/CoronaWatchNL/raw/master/data-geo/data-municipal/RIVM_NL_municipal.csv', index_col=0)
df.index = pd.to_datetime(df.index)

fix_cumulative_vals(df)
print(check_if_cumulative(df))
```

**Comment by J535D165** [comment]
Thanks for the script. Very useful to many of us. 

Correcting introduces a new problem to some users because the totals don't add up. I'm thinking about an additional column with remarks. The moment a correction is observed, we add a note to the row. The note can link to this issue and your code. Would this help?

**Comment by Sikerdebaard** [comment]
This would certainly help. :)
